### ISSUE TITLE
Issue in maintaining segment key when splicing the segment

### ISSUE THREAD

**Issue by jagadishkamathk** [kuu/hls-parser#73] opened 2020-09-14 15:37 UTC
When I replace an existing segment with a new segment with a different key parameters, the replaced segment has correct key information. However, the original segments which follow replaced segment have wrong keys. 

Sample code to reproduce this issue

```
const hls   =  require("hls-parser")
const axios = require("axios")
axios.get("https://k7q5a5e5.ssl.hwcdn.net/files/company/5e2f4a02199f0c33444d9403/assets/videos/5e311e889ba3f225c86c0b52/vod/5e311e889ba3f225c86c0b52_Layer_1.m3u8")
.then(function(manifest_data) {
   var media_manifest = hls.parse(manifest_data.data);
   var temp = JSON.parse(JSON.stringify(media_manifest.segments[100]));
   temp.key.uri="dummy.enc";
   media_manifest.segments.splice(100, 1, temp);
   console.log(hls.stringify(media_manifest))
});

**Comment by kuu** [comment] 2020-09-15 01:03
EXT-X-KEY applies to all subsequent segments until another EXT-X-KEY appears in the same playlist.

If you want to apply "dummy.enc" only to 100th segment and the subsequent segments still need to refer to the original key, please set the `key` property of the 101th segment so that the subsequent segments should be decrypted with the original key.

**Comment by kuu** [comment] 2020-09-15 01:38
Correcting my prev comment.
Even if you set the `key` property of the 101th segment, it won't be reflected to the output because HLS.stringify() is doing a redundancy check.
I'll figure out how to fix the issue.

**Comment by jagadishkamathk** [comment] 2020-09-15 07:37
Thanks for the confirmation. Is there workaround for now?

**Comment by kuu** [comment] 2020-09-15 11:04
If it's allowed to add params or hashes to the key's URL (the key server should ignore the params or hashes) the following workaround should work:

```
const hls   =  require("hls-parser")
const axios = require("axios")
const url = "https://k7q5a5e5.ssl.hwcdn.net/files/company/5e2f4a02199f0c33444d9403/assets/videos/5e311e889ba3f225c86c0b52/vod/5e311e889ba3f225c86c0b52_Layer_1.m3u8";

axios.get(url)
.then(function(manifest_data) {
   var media_manifest = hls.parse(manifest_data.data);

   console.log('--- Original start ---');
   console.log(hls.stringify(media_manifest));
   console.log('--- Original end ---');

   var temp = JSON.parse(JSON.stringify(media_manifest.segments[100]));
   temp.key.uri="dummy.enc";
   media_manifest.segments.splice(100, 1, temp);

   const originalKey = Object.assign({}, media_manifest.segments[0].key);
   originalKey.uri += `#${new Date().getTime()}`; // Adding unique hash
   media_manifest.segments[101].key = originalKey;
   console.log(media_manifest.segments[101]);

   console.log('--- Modified start ---');
   console.log(hls.stringify(media_manifest));
   console.log('--- Modified end ---');
});
```

It's similar to cache busting :)

**Comment by kuu** [comment] 2020-09-15 14:56
@jagadishkamathk I made a fix and published it as v0.6.3.
Can you upgrade and confirm if the issue is gone?

Thanks,

Kuu

**Comment by jagadishkamathk** [comment] 2020-09-15 15:59
Works for me. Thank you so much for the quick fix. Appreciate it

**Comment by kuu** [comment] 2020-09-15 22:33
Thanks for confirming that.
Will close this issue.
Thanks for letting me know the bug :)

**Closed by kuu** 2020-09-15 22:33 UTC
